apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: availability
  namespace: experiments
  title: Availability System
  description: Availability system
spec:
  owner: experiment-finance-alpha
  domain: finance
  manager: ferko.financak