apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: saf-t
  namespace: experiments
  title: SAF-T System
  description: SAF-T system
spec:
  owner: experiment-finance-alpha
  domain: finance
  manager: ferko.financak